### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by shamblesides** [express-vue/vue-pronto#90]
Hello,

This is a great project. I've been using it (through express-vue) and it works great.

I was wondering if we could remove the "Precached -> /path/to/component.vue" messages in production. They aren't useful and they add clutter to my project's output that I cannot disable. Can we do one of the following:

* Remove them entirely
* Don't show them unless an environment variable is set
* Don't show them unless an argument is passed to the Pronto constructor

If you let me know your preference, I can open up a pull request that accomplishes that. Thank you!

**Comment by danielcherubini** [comment]
this has been changed a lot since then. 
https://github.com/express-vue/express-vue#migration-to-webpack-renderer

there's also a CLI for building for production...

`expressvue build .`

remember to include the `.expressvue` folder into your production container or whatever...

it's much quieter for prod
